[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
eth_rpc_url = "https://testnet-rpc.monad.xyz"
chain_id = 10143
solc_version = "0.8.30"
optimizer = false
evm_version = "cancun"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
